### ISSUE TITLE
Carmen Debug Options

### ISSUE THREAD

**Issue by ingalls** [mapbox/carmen#220]
At the moment Carmen is very difficult to debug. Carmen should use the `DEBUG` flag to tell it to log the current valid results at the end of each operation.

Logging at the end of
- [x] Grid lookup
- [x] PhraseMatch
- [x] Spatial Match

cc/ @yhahn @karenzshea

**Comment by yhahn** [comment]
My recommendation over just dumping results at various stages (which can be so large they they are not very useful) would be to have an option for tracing a specific feature ID through the process.

------

When I debug manually the situation I'm usually in is:

> Some feature N that I'm expecting to see is not in the result set.

So then I

- First figure out the feature ID that I'm expecting to see.
- Is it in the grid results of phraseMatch? What is the relev + reason + count of the feature at this point?
- Is it in the results of spatialMatch? What is the relev + reason + count of the feature at this point? Does it stack with other features?
- Does it make it past verifyMatch?

**In theory this could all be added to https://github.com/mapbox/carmen/blob/master/lib/geocode.js without touching any of the underlying functions since this lib has access to each one's input/output.**
