### ISSUE TITLE
Mixed score + distance when sorting

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#276]
Per convo + testing with @ian29 we're looking for overall behavior to be something like:

- High scored features always beat others, (`new york => New York (place) vs New York Ave (road)`)
- Unless you're very close to a feature ('New York Ave (road)`)

Finding the right behavior is going to take some testing here that I'm not sure how to do/capture yet.

**Comment by ian29** [comment]
picking this up. 

it looks like to make accurate use of scores, we'll actually want to include index type in the mix, so that:

- as proximity approaches zero, scores become more important in sorting, and indexes become irrelevant
- as proximity approaches infinity (or some super high threshold), indexes become more important and scores become irrelevant

**Comment by ian29** [comment]
after voicing with @ingalls, not so sure of the above. at least, mixing score + index sorts only makes sense when proximity is present. not so sure about mixing score and index when proximity is absent. as long as you have confidence in your score having higher values for higher-order results i.e. places / countries, mixing score and index should not be necessary when proximity is not supplied.

**Comment by yhahn** [comment]
Let's hold on this for now -- I have planz ; )

**Comment by yhahn** [comment]
https://github.com/mapbox/carmen/pull/297
