### ISSUE TITLE
Is center a centroid? Should it be called centroid?

### ISSUE THREAD

**Issue by tmcw** [mapbox/carmen#407]

**Comment by yhahn** [comment]
> Is center a centroid?

No, it's more often a "representative point" on the feature if it's a linestring or polygon and the point itself if the feature geometry is a point.

Open to new names : )

**Comment by twbell** [comment]
Centroids can imes have associated geometric rules, like they must be *on* the geometry, e.g. a crescent-moon shape.  Unsure if we need to be too specific here; if not suggest "centroid" is an appropriate shorthand for a point-representation of a feature.

**Comment by apendleton** [comment]
Oftentimes the center points are not close to the actual centroid; in many cities they're over the downtown area, for an example. It's basically where you would expect the label to be on a map. But in, say, Seattle, where downtown is right on the water and most of the city is north of downtown, you could expect the center point and the centroid are quite distinct, and it'd be confusing to conflate the two. More generally, if we're going to use a jargon word with a specific technical meaning, we should use it to mean that thing, otherwise we should use a general term with a meaning that's less specific.

**Comment by tmcw** [comment]
Okay, fine with center being center-as-in-likely-point-on-surface-but-not-always.

**Comment by ingalls** [comment]
`centre`

![](https://s-media-cache-ak0.pinimg.com/236x/f4/9b/f9/f49bf920f6eb984e4355695d58f4f130.jpg)
