### ISSUE TITLE
Setup tests for multipart-indexing

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#445]
Let's walk through this backlog together and I can teach you about parts of carmen as we go along.

- [x] create new branch from master
- [x] add `test/index.merge.test.js` -- we can use the first parts of `index.test.js` as a guide to how to create and index some features
- [x] we'll add tests for 3 different mbtiles indexes. Each test will
  - index A: lines 1-100
  - index B: lines 101-200,
  - index C: lines 201-254
  - of the indexing datasource (https://github.com/mapbox/carmen/blob/master/test/fixtures/docs.jsonl)
  - query each index and confirm it has some of the features from its lines (but not features from the other lines)
- [ ] **SKIP** - merge the indexes and query for any of the features. We'll add this once @apendleton's branch is up + merged into ours.
- [ ] cleanup the indexes

cc @aarthykc

**Comment by apendleton** [comment]
The current state of affairs: the following things are being merged in the merge-redux branch:
* freq
* stat (so: the DAWG cache)
* feature
* grid

Missing from this list is vector tiles, which are not being merged in carmen at present. We don't have a good plan for merging vector tiles, and for production use our current plan is to not try, and instead stash feature geojson during the indexing process, and then concatenate that and build vector tiles out of it outside of carmen. Preliminarily this looks like it will work fine, but leaves us with the question of how to test merging within carmen. The testing strategy so far anticipates being able to perform geocodes on merged indexes, but without vector tiles in the merged indexes, this won't work. At this point, I see a few paths forward for testing:
* **make tests lower-level:** rather than attempting to perform geocodes, test the contents of individual types in the merged index (e.g., contents of individual freq, feature, or grid shards) against what we expect the values to be
  * *harder variant:* rather than testing against what we think the values should be, separately index the combined data in a single pass, so that we have two indexes, one the result of a merge, and one from an all-at-once build, that should contain the same data, and then compare the contents of the index. This will be challenging because carmen's decision-making about dropping low-value features is based on the frequency distribution of the terms it's indexing at any given time, and it may make slightly different decisions when building sub-indexes than when building the full index, which might lead to small differences in, at a minimum, the DAWG contents and the feature index, and probably also freq and grid. We'd need to build in a fudge factor to make this work right.
* **mimic the production vector tile merge strategy:** store the geojson of the features we're indexing in tests as we index them, and manually combine them after merge and add them to tiles in the merged index. This would let us run geocodes to confirm that the other datatypes in the index are correct.
* **use mbtiles instead of api-mem for the merge tests:** this would let us use similar tooling for tests as we intend to use in production, rather than having to reinvent it on top of api-mem

I'm not sure which of these is the best way forward.

**Comment by yhahn** [comment]
Done!
