### ISSUE TITLE
thoughts on fuzzy text search

### ISSUE THREAD

**Issue by ansis** [mapbox/carmen#495]
Yeah, this is hard

I'm seeing three intertwined parts of the problem:
## 1. deciding what counts as a fuzzy match

The usual approach is to count words as fuzzy matches if they are within a certain [edit distance](https://en.wikipedia.org/wiki/Edit_distance) of each other. [Levenshtein](https://en.wikipedia.org/wiki/Levenshtein_distance) and [Damerau-Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) are the most common distance metrics. They're simple and they covers a majority of errors in many languages. I think it works well in languages who's alphabets are based on the latin alphabet but I have no idea how it works for other languages. 2 is a common max edit distance.

Edit distance won't help identify matches for:
- complex phonetic misspellings
- missing synonyms, alternate names, etc

You could try to handle phonetic matches using a [Soundex](https://en.wikipedia.org/wiki/Soundex)-like algorithm. Soundex tries to encode words so that english homophones have the same encoding. It might be possible to machine learn a better version of Soundex but that seems complicated. These approaches have a couple big problems:
- each language needs a significant amount of custom engineering
- we don't know what language a query is in
- languages are messy and have exceptions that wouldn't be handled correctly

Another approach is to learn misspellings and their corrections by looking at misspellings that people correct themselves. For example: a user searches for `M` and doesn't get the results they want. The user corrects the search to `W` and finds the result. If enough people search `M` and then correct it to `W`, then `W` can be saved as a correction for `M`. This is a good way to get more complex corrections but it's unlikely to cover all the small possible typos.

**It seems like Damerau-Levenshtein combined with separate learned-from-user-corrections could work well. Language-specific approaches do _not_ seem common.**
## 2. figuring out how to quickly find the fuzzy matches for any query

Ok, let's assume you want to find fuzzy matches based on Damerau-Levenshtein and learned corrections. Learned corrections are relatively easy. Just index each (misspelling, correction) pair with a score. Learning the corrections is complicated but the changes to Carmen should be fairly simple.

Edit distance matching is harder because there is a massive number of words within an edit distance of 2 from another word. [Dennis' fast similarity search paper](http://arxiv.org/pdf/1008.1191v2.pdf) reduces the amount of index entries to a more reasonable, but still large, number. [This is the basic idea](https://gist.github.com/ansis/8d15bc4519e50c29c14c5b44552f56da).

Could some of the possible edit-distance matches be eliminated from the index to reduce the amount of work that needs to be done? I don't think so. While some words within the allowed edit distance are unlikely enough that they could be eliminated, the deletion approach doesn't let you drop individual entries. Any approach that tries to explicitly spell out all reasonably-possible typos will probably be more expensive.

In Carmen these corrections could be done within phrasematch. It would require a much bigger dictcache and more dictcache lookups. It would not affect the size of the grid index.

There are some possible variations. Corrections could be done on individual tokens or on entire phrases. Matches could be searched in a hash table or in a dawg/trie to allow autocomplete without degens.
## 3. making it possible to geocode the multiple corrected phrases without killing performance

Ok, let's assume step 2 is implemented and a query can be quickly corrected into a set of possible phrases. Having multiple possible phrases will result in more grid lookups that before. The fanning across many shards would happen whether they are indexed by prefix or hash. **This is a slightly worse version of the problems encountered in the current degenless work**. @apendleton's explanation of those problems: https://gist.github.com/ansis/e4cd448f6372f7926477bc046c18e89b

_WARNING: I haven't actually spent the time to profile Carmen and I haven't worked with AWS at all. The following guesses are just guesses._

The current approach to sharding works poorly with degenless and would work even more poorly with fuzzy searching. It will get worse as more data is added to the indexes.

Carmen is already slow. I'm guessing it's partially:
- waiting for shards or vector tiles to load
- regular CPU work

Carmen indexes are sharded by phrase. Most search engines are sharded and distributed by document. The equivalent in Carmen would be to shard spatially or by stack. If Carmen were more similar to a regular search engine it might look something like this:

The main Carmen server performs phrasematch and correction on a query. It then distributes the query to several servers. Each of those servers performs spatialmatch and verifymatch on the query for a specific stack or spatial area. The entire grid index for the stack/area would live in memory on each of those subservers. The main Carmen server collects and merges the results from all the servers.

Upsides:
- Parallelizes cpu work
- Never needs to fetch and wait for grid shards
- Scales better as more data is added to the index

Downsides:
- Harder to test correctness with large indexes. You can't have a single small server that only loads what is necessary to test a single query.
- You have multiple kinds of servers instead of one. I have no idea how much complexity this adds.
- Switching to this approach would be a lot of work

---

I'm imagining:
Matches would be defined by Levenshtein + corrections learned from logs. Matching would happen roughly as in Dennis's fast similarity search paper. None of this is too exciting. But I'm _guessing_ that Carmen would need to change the way it shards and distributes work for this to be performant.

That seems like a massive change. Does anyone see a better way?

@apendleton @sbma44 @yhahn

**Comment by apendleton** [comment]
This is great, and accurately matches my understanding of the problem space. Worth noting, though, that:

> missing synonyms, alternate names, etc

is a significant subproblem for us, so in some sense "fuzzy text search" is actually two different problems that, I suspect, will need separate algorithm/datastructure solutions. We see the synonym problem most often with substitutions of things like "route" for "highway," etc., and as you note, solutions aimed at solving misspellings get us nowhere there. I've had thoughts about using some kind of [word embedding](https://en.wikipedia.org/wiki/Word_embedding) strategy to help us cluster similar words per language to facilitate that kind of correction, but don't have a fully fleshed out idea there.

Regarding Soundex: we've talked about this before, and the idea might have merit, but we probably couldn't go with Soundex specifically because it's English-specific. We could try something in the [Metaphone](https://en.wikipedia.org/wiki/Metaphone) family, though, which ostensibly has broader language support. (For that matter, even Levenshtein is complicated language-wise once you get into CJK languages: a one-character change in Mandarin is not at all equivalent to a one-character change in English).

Anyhow, for misspellings, yes, I think constructing an additional datastructure at index time specifically to handle misspellings is the way to go (I had thought BK-trees, but if that paper proposes a better structure, all the better). I suspect doing it word-wise is the way to go to keep memory usage manageable, and there may also be some 80/20 kinds of solutions where the vast majority of misspellings are of a fairly small number of words and we may be able to achieve a high fix rate with a relatively small word corpus, which would definitely be worth pursuing because our memory usage story is obviously not great at the moment. Learning this stuff from logs is an interesting idea, but we have no easy way to assess whether users found what they wanted (we don't get feedback on user selections), so that might be challenging.

As for speed mitigation: yes, I think our performance is at a point now where we can't move forward with any algorithmic changes that have associated speed hits until we address latency. The sharding strategy you're proposing seems like it has potential, though I haven't thought through all of the ramifications... it's somewhat orthogonal to this problem though, so might be worth exploring that (or other speed mitigation strategies) separately first?

Sorry if that was a bit rambly, but hopefully useful.

**Comment by sbma44** [comment]
> As for speed mitigation: yes, I think our performance is at a point now where we can't move forward with any algorithmic changes that have associated speed hits until we address latency. The sharding strategy you're proposing seems like it has potential, though I haven't thought through all of the ramifications... it's somewhat orthogonal to this problem though, so might be worth exploring that (or other speed mitigation strategies) separately first?

I think ^^^ is probably the crux of the situation. @yhahn has said, semi-cryptically, that he thinks there are things we can do to improve performance but none of them are easy & we should clean up other quests first. This sounds right to me but I know it might leave you without a clear set of priorities, @ansis.

As for the specifics of the implementation of fuzzy search: my understanding of BK trees made me think we could artificially manipulate them to handle the "swapped tokens" case. Dennis's paper's approach is obviously clever and intellectually consistent with how we approach other parts of language handling in carmen, but I need to think some more about how it might integrate with the token swap problem.

**Comment by aarthykc** [comment]
We did this in #719
