### ISSUE TITLE
Runtime token replacement last stretch...

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#515]
Debugging some IRL scenarios with https://github.com/mapbox/carmen/pull/476 the last stragglers seem to be cases where we can deconstruct what's happening like this:

tokens:

```
north => n
```

Becomes

```
(\\W|^)north(\\W|$) => n
(\\W|^)n(\\W|$) => north
```

_(regex word boundaries)_

These falsely split on high range unicode characters creating totally bogus permutations for DAWG lookup like:

```
Original query:
  General Pirán Argentina

One of the token-replaced permutations:
  General Piránorth Argentina
```

:grimacing: sometimes when this happens the resulting permutation actually matches something :confounded: and honestly we should have never even considered the permutation legit in the first place.
### Possible solutions
- Change how the token replacement function works (https://github.com/mapbox/carmen/blob/master/lib/util/token.js#L48-L58). For example we could
  - use the tokenizer which _does_ have a more sophisticated concept of word boundary and then replace individual tokens post-tokenization. We would remove the weird `(\\W)` word boundary portions of our regex.
- Use a more sophisticated word boundary concept around our computed token regexes.
- Use xregexp or other library that is more unicode aware.
- Other?

_Any/all of these approaches could have a serious impact on performance. Token replacement can get very expensive so we should profile._
### Next actions
- [x] Branch off of https://github.com/mapbox/carmen/pull/476
- [x] Add some unit tests for this word boundary vs unicode characters fail case
- [x] Implement token replacement in a way where these false permutations are not considered

**Comment by ansis** [comment]
I started looking into this and it seemed like the bidirectional token replacement in #476 only works for basic string tokens. Regex tokens don't work because they can't just be swapped. Source tokens that use regex are pretty rare though. From what I could find, the only mapbox sources that use token replacement with regex are the `kr` ones:
```json
"geocoder_tokens": {
            "(?<root>\\w+)-dong": "${root}dong",
            "(?<root>\\w+)-si": "${root}si",
            "(?<root>\\w+)-gu": "${root}gu",
            "(?<root>\\w+)-gun": "${root}gun"
        }
```
We either need to:
- provide the regex for the reverse replacement
- approximate the replacement without regex  `"-dong": "dong"` and completely drop regex support for source token replacement

Am I missing some more uses of regex for source token replacement?

----

There is a ton of complexity [here](https://github.com/mapbox/carmen/blob/dfd9ecf6588da21fb62626c2df5579e32bd331f9/lib/util/token.js#L7-L60) that never seems to be used for source_tokens. It used to be used for global ones but that changed in #494?

@sbma44 provided this background on xregexp
> yeah, xregexp turned out to be super-slow
> but necessary for some token patterns
> so we detect when a regex requires it by looking for named capture groups
> if we could drop xregexp it'd be great but I doubt we can

Is that still the case? Are things broken or using xregexp through some path I'm not seeing?

---

> use the tokenizer which does have a more sophisticated concept of word boundary and then replace individual tokens post-tokenization. 

This approach seems to be solid so far.

**Comment by sbma44** [comment]
> Is that still the case?

The XRegExp code is definitely still in place -- the `named` property is how we test for the necessity of XRegExp use. This is only run when creating a carmen instance, avoiding the slowness associated with XRegExp.
https://github.com/mapbox/carmen/blob/1c540fb546caea436614b49d9123eb8736423c09/lib/util/token.js#L29

Bigger picture: 
- XRegExp is not necessary for the Korean tokens, which operate on latin characters
- CJK languages mercifully don't seem to use abbreviations much
- Writing the reverse regex for the Korean tokens (and any others we come up with) seems reasonable and easy enough. While we're at it we should move to numbered capture groups instead of named ones for the performance improvement.
- I think we will probably want to keep XRegExp in our arsenal even though we appear to not be using it right now -- my guess would be that Cyrillic languages' affection for diminutive forms means they feature plenty of abbreviations, though I am probably the least qualified person on this ticket to speculate about that.

I say all of the above apart from the word boundary issue.

**Comment by ansis** [comment]
@sbma44 thanks for the explanation.

https://github.com/mapbox/carmen/pull/517 implements a fix for the original issue

Bidirectional replacement is still broken for replacers that use regex.

**Comment by miccolis** [comment]
>  I think we will probably want to keep XRegExp in our arsenal even though we appear to not be using it right now

It appears that we're still not using named regular expressions & it's two years after @sbma44's comment above.  At this point it seems pretty clear that the complexity it adds to the code isn't adding any value and so probably isn't work bringing with us. I vote to remove.

**Comment by miccolis** [comment]
Upon reflection it seems like we have fixed the original issue (incorrect matches based on tokenized text) with https://github.com/mapbox/carmen/pull/795

Closing.
