### ISSUE TITLE
not writing our own key-value store

### ISSUE THREAD

**Issue by ansis** [mapbox/carmen#549]
*disclaimer: I don't know that much about carmen-cache. just raising some questions*

Carmen-cache is a self-written database. This may have made sense when we were loading parts of the index on demand, but now that we're just getting stuff from disk* we should think about using something else. We don't need to shard by key anymore so carmen-cache becomes a regular key-value store that reads from disk. Databases are hard so we should use one written by someone else instead of writing our own. Something like [RocksDB](http://rocksdb.org/).

At index-time add everything to the db. Transfer the entire db to s3. Download it and use it.

\* *ok, not completely yet*

### I'd hope this would:

- remove a lot of complexity and code from carmen-cache
- make random accesses of features and grid lists significantly cheaper
- reduce complexity in carmen and increase accuracy by letting us do things that used to be expensive:
    - loading features for more/all spatialmatches instead of the 10 best
         - get rid of approximate scores! access the list of languages from the features!
    - if grid lookups are cheaper, you could load grid lists for all phrasematches
        - you could reverse some of the logic of `stackable` and `coalesce` by matching by tile (roughly linear) before creating the stacks. This could be faster and get rid of approximations.
    - this might make it easier to implement degenless/strings-attached
- step towards making it viable to run carmen locally with all the data

### Potential challenges:
- would this be less space-efficient, and if yes, by how much?
- how hard is it to drop s3/sharded sources completely

----

How I started thinking about this:
"Why do we have to have all these approximations? Accessing things used to be really expensive. Now that things are on disk can we get rid of some? Not sure, but it seems like it should be possible to make accesses even cheaper. What would change in carmen if accessing things from the index were cheaper?"

@apendleton @yhahn 
I know there were good reasons for doing it the way it's done, but now that some things have changed do you think using a real key-value store would improve performance and reduce complexity?

**Comment by apendleton** [comment]
Not opposed, but I think it will be hard.

> would this be less space-efficient, and if yes, by how much

If we preserve the current delta-encoding of grids and use protobuf varints for grid lists, probably won't change by that much, but then we're still largely inventing our own database, so we'll need to carefully consider whether it's worth it. If not, I think it will be much less space-efficient.

> this might make it easier to implement degenless/strings-attached

I think strings-attached will ultimately depend on having a precomputed index/datastructure that can very efficiently do a "retrieve all values for keys that start with X" operation, which is not an operation for which most off-the-shelf databases are optimized (at least without a bunch of extra indirection). If we can find an off-the-shelf database that can do that well, though, maybe?

We also, more generally, will need to reckon with the fact that databases are hard to write, but a lot of the complexity comes from features we don't need, and those features introduce overhead that we would otherwise not have to worry about. Our databases don't have to deal with writes at query time at all, for instance, ever. Reads and writes never occur at the same, writes are append-only (no updates, no deletes), there are no locks that need to ever be checked, etc.

So... I'm definitely curious. But guarded.

**Comment by ansis** [comment]
> If we preserve the current delta-encoding of grids and use protobuf varints for grid lists, probably won't change by that much, but then we're still largely inventing our own database, 

What I was thinking of as _database_ is the part that handles reading from storage and caching. How values are encoded seems separate from that and could stay basically the same.

> I think strings-attached will ultimately depend on having a precomputed index/datastructure that can very efficiently do a "retrieve all values for keys that start with X" operation

Range queries should be pretty fast in RocksDB and similar key-value stores, especially since we can compact it completely after indexing is done. Seek an iterator to the first possible value and keep calling next().

Or if this structure is going to live 100% in memory you might not gain anything from this but you also don't gain much from the current way.

> but a lot of the complexity comes from features we don't need, and those features introduce overhead that we would otherwise not have to worry about.

Yep. I'm completely guessing here, but I think the overhead of this could still be lower than the overhead of our own implementation. I don't know much about this stuff but I'd guess the main bottleneck is how many pages/blocks you need to read from and I think their implementation would be better at that

**Comment by ansis** [comment]
More generally, a lot of the decisions on how to index and access things depend on the how expensive accesses are (both in terms of latency and throughput) and how limited storage is. Things that made sense before might not make sense now, and things that make sense now might not make sense in the future.

@yhahn you've hinted that that we might move away from disk-based storage at some point? What do you have in mind?

**Comment by apendleton** [comment]
@ansis so thinking more about this, I think I'm 👍 to proceed here. I think the least invasive path to an MVP would look like:
* access to/from rocksdb is done from C++ in carmen-cache
* values are still protobuf-encoded int lists
* interfaces to/from carmen-cache stay largely the same, with the exception of the omission of currently-required shard_id

This confines most changes, with the exception of the change in signature, to within carmen-indexer __get/__set (and merge, I guess), and I think could be accomplished quickly. We could start with carmen/carmen-cache@strings-attached, I think? And change the prefix-matching to a range query, as you proposed. Coalesce single/multi, in particular, would continue to work pretty much without changes.

The main question from how the finished product eventually gets stored (since shards now end up in a sqlite table in our final output file). We'd presumably need to rework what `pack` does, and do... something... with the resulting rocksdb file. Maybe shove it in a sqlite3 blob?

Anyhow, does this comport with your thoughts on how we'd do this, or were you thinking of something that accessed rocksdb directly from JS, and if so, what shape did you imagine it would have?

**Comment by ansis** [comment]
sounds like a good plan

> The main question from how the finished product eventually gets stored (since shards now end up in a sqlite table in our final output file). We'd presumably need to rework what pack does, and do... something... with the resulting rocksdb file. Maybe shove it in a sqlite3 blob?

We could do that or we could make a separate archive with it and leave only the tiles in the sqlite.

> or were you thinking of something that accessed rocksdb directly from JS

Nope, I think accessing it from c++ is good

**Comment by ingalls** [comment]
Rocksdb 🎉
