### ISSUE TITLE
Accept antimeridian-crossing bboxes

### ISSUE THREAD

**Issue by mattficke** [mapbox/carmen#574]
### Context

Carmen currently implements and enforces bounding boxes per the [2008 GeoJSON spec](http://geojson.org/geojson-spec.html#bounding-boxes):

>The value of the bbox member must be a 2*n array where n is the number of dimensions represented in the contained geometries, with the lowest values for all axes followed by the highest values.

For features with geometries that cross the antimeridian (such as the United States), this leads to flawed bounding boxes.

#### Current US bbox:
![image](https://cloud.githubusercontent.com/assets/9308599/22131472/7b06b558-de68-11e6-9409-5c84b198ad37.png)

#### What it should be:

![image](https://cloud.githubusercontent.com/assets/9308599/22131566/2dedfd5c-de69-11e6-923a-4ac0b7c3c64e.png)

### Next Steps
To fix this, we should implement the updated bbox spec from [RFC 7946](https://tools.ietf.org/html/rfc7946#section-5):
>The value of the bbox member MUST be an array of
   length 2*n where n is the number of dimensions represented in the
   contained geometries, with all axes of the most southwesterly point
   followed by all axes of the more northeasterly point.

BBoxes are used both at indexing time and at query time.

* Indexer: if I'm reading the [turf docs](http://turfjs.org/docs/#bbox) correctly, this can be solved by simply upgrading to a recent version of `turf-bbox`. Turf can calculate spec-compliant bboxes in `west, south, east, north` order.
* Query time: used in the [bbox filter](https://github.com/mapbox/carmen/pull/457), this will need to be modified to accept SW/NE bboxes. Trickiest part will likely be in carmen-cache, where we'll need to properly handle the conversion to z/x/y tile coords in a more sophisticated manner.

In case we need to do our own bbox calculations, capturing @apendleton's notes from chat:

> * if the geometry exists entirely in the eastern or western hemisphere, continue as now
> * if not:
>     * split the geometry at the prime meridian and calculate separate bounding boxes for the eastern half and western half
>     * determine the width of the PM-crossing bounding box by adding (0 - westMinX) + (eastMaxX - 0)
>     * determine the size of the AM-crossing bounding box by adding (westMaxX - -180) + (180 - eastMinX)
>     * pick the smaller of the two, then:
>         * if PM-crossing wins, bbox goes from westMinX to eastMaxX
>         * if AM-rossing wins, bbox goes from eastMinX to westMaxX

cc @tmcw for confirmation on the Turf question, and @sgillies for general GeoJSON spirit guidance.

**Comment by apendleton** [comment]
Those turf docs are misleading, I think (at least kind of -- the bboxes that are generated are, indeed, in WSEN order, but they're not AM-crossing, so they're not the smallest-possible WSEN bboxes). The function just looks for the minimum X value and maximum X value, Cartesian-geometry-wise: https://github.com/Turfjs/turf/blob/master/packages/turf-bbox/index.js

And it looks like the doc string has actually been updated to reflect that, but the docs on the website are behind.

Also: at query time we don't just use bboxes for the filter. They get used in a bunch of checks even for non-filtered queries to test for, e.g., correct stacking before the fetching of full feature geometry. Fortunately most of this has been abstracted into a util file (`util/bbox.js`), but all three of its functions will need to be made AM-aware. I think in all cases it will probably make sense to add a test of AM-crossing, then special-case AM-crossing bboxes by decomposing into two non-AM-crossing boxes, recursing, and combining their results, but I'm the least sure about the viability of that approach for `insideTile`.

Sidenote, though (as I partly said in the meeting): if we want to continue to supply old-style bboxes in current API versions (which we probably do, because this is a breaking change), we'd need to either calculate both at index time, or calculate the old-style kind at render time from the feature geometry. If we do the former, we could conceivably just use the old-style ones for all internal calculations and only use the new-style ones for user-facing output, which then really would mean the only query-time implications would be for filtering, and we could sidestep concerns about, e.g., tile covers. It *would* mean we'd forego some potential efficiencies, though, from shrinking our bboxes for AM-crossing features like the US and Russia, so I'm not sure this is the right path forward.

**Comment by tmcw** [comment]
The current [Turf docs for bbox](http://turfjs.org/docs.html#bbox) only claim ` [ minX, minY, maxX, maxY ] order`, which accurately describes what Turf does. Turf doesn't yet enforce or expect RFC GeoJSON - so turf-bbox gives a 2008 answer.

@apendleton's approach sounds correct for carmen's issues.

**Comment by mattficke** [comment]
See also https://github.com/mapbox/mapbox-gl-js/issues/2415 & https://github.com/mapbox/mapbox-gl-js/pull/2414 for related work on this issue.

**Comment by yhahn** [comment]
Per :speaking_head: the biggest challenge might be making sure consumers are also capable of handling an antimeridian-crossing bbox.

One way we could approach this:

- Enable antimeridian bboxes in carmen
- Add a backwards compatible migration util function to carmen that chooses the larger side of the bbox if you want to force `minx, miny, maxx, maxy` style bbox
- For carmen users (like Mapbox) that need to preserve backwards compatibility on a particular API version they can run the migration and then remove it on newer API versions

**Comment by mattficke** [comment]
🚀 in #646. Still need to do this for the bbox query param, but will track that separately.
