### ISSUE TITLE
Multilingual names

### ISSUE THREAD

**Issue by tmcw** [mapbox/carmen#68]
`Москва` should work for Moscow, and so on.

**Comment by camilleanne** [comment]
Technically possible with #319, but will become functionally a data issue.

**Comment by apendleton** [comment]
I pontificated for awhile out loud about this maybe yesterday, but should brain-dump here too, I think... but this is a really hard problem, because there's not a single standard romanization for Russian (see, for example, [this terrifying table](https://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table)). For "Moscow," where there's a single standard English name, it's straightforward and can be approached with per-language fields, but for, say, street names, there will be one canonical Cyrillic spelling and an arbitrary number of potentially-equally-valid Romanizations people might use for search.

I was asked while in Ukraine a few weeks ago for advice on building a search UI over the names of Ukrainian politicians; the organization building the tool wanted to allow search in both Cyrillic (which matched the source data) and Latin letters, and wanted to know how best to handle the varied Romanization. The example they gave, if I remember right, was for "Sergey." Ukrainian is bilingual, so if that name were transliterated from Cyrillic according to Russian rules, it might be either "Sergey" or "Sergei." But the name is differently pronounced in Ukrainian; the last vowel is different, and romanized either "ii" or "iy," and the Cyrillic letter that makes a "g" sound when used in Russian instead makes [this sound](https://en.wikipedia.org/wiki/Voiced_glottal_fricative), which has no precise English equivalent, so it's variously transliterated as "g" as in Russian, or as "h." So, this person in Ukraine with one name in Cyrillic might have six different valid transliterations into English:
* Sergey
* Sergei
* Sergii
* Sergiy
* Serhii
* Serhiy

And as far as I could tell, each letter with more than one choice multiplied the number of possible transliterations for the whole word, so long words could have way more than six. And you might also have to consider other Cyrillic users (Belorussian, etc.) if building a general solution. Probably can't be done with just an extra field per language, at a minimum... I had no idea what to tell the Ukrainians asking me, but one of my Sunlight colleagues recommended exploring things like Metaphone transformations as a good place to start.
