### ISSUE TITLE
Querying default indexes

### ISSUE THREAD

**Issue by Gadda27** [mapbox/carmen#769]
### Context

In the [documentation](https://github.com/mapbox/carmen#command-line-scripts) it says you can query default indexes in the command line. However this seems to be outdated. The scripts folder doesn't exist. 
Is there an updated way to query those default indexes used by mapbox in their geocoding API?

**Comment by ingalls** [comment]
@Gadda27 We used to include a small places index as an example for users to query if they were experimenting with setting up and developing on carmen. Since then we have found the examples in our `test/acceptance` directory to be far better suited for showing different ways to configure and use carmen.

Although Carmen is open-source, the data that powers the Mapbox Geocoding API is not. If you would like to do geocoding from the command line, signing up for a  mapbox account, obtaining an access token and then using our command line interface is an option: https://github.com/mapbox/mapbox-cli-py#geocoding
