### ISSUE TITLE
Using carmen and tilelive-s3.

### ISSUE THREAD

**Issue by honjo2** [mapbox/carmen#892]
I'm trying MVT based geocoder using carmen and tilelive-s3.

However, looking at the source code, it seems that only GeoJSON is supported.

https://github.com/mapbox/carmen/blob/v30.2.0/lib/util/feature.js#L138
https://github.com/mapbox/carmen/blob/v30.2.0/lib/util/feature.js#L234
https://github.com/mapbox/tilelive-s3/blob/v7.0.1/lib/index.js#L517

Am I misunderstanding?

**Comment by ingalls** [comment]
Hey @honjo2,

Yes you are correct that to create carmen search indexes you need to start with the original GeoJSON data. A vector tile layer (mbtiles/s3/etc) cannot be converted into a searchable index.

To start creating indexes you first pass the GeoJSON features into the [bin/carmen.index.js](https://github.com/mapbox/carmen/blob/master/bin/carmen-index.js). Note that GeoJSON features have to have a few carmen specific properties as defined in our [data sources](https://github.com/mapbox/carmen/blob/master/docs/data-sources.md) document.

Once the forward search indexes are created, the data must then be vectorized. We usually use a tool such as tippecanoe](https://github.com/mapbox/tippecanoe). 

The forward search index, alongside the created vector tiles form a carmen compatible index that can be used when a Carmen instance is instantiated.

Just read through the docs and I'm afraid it's been years since we've attempted to use an s3 tilelive source. I suspect that this is no longer possible. We've done a massive amount of work to optimize the indexes to be small and efficient enough to fit on a single machine.

**Comment by honjo2** [comment]
I understand.Thank you for your answer.
